CREATE TABLE tickets
  (ticket_number varchar(20) PRIMARY KEY,
  status varchar(20),
  ticket_name varchar(20),
  date_opened date,
  date_last_updated date,
  session_date date,
  engineer_name varchar(20),
  engineer_email varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  assignee_name varchar(20),
  assignee_email varchar(20),
  genre varchar(20),
  number_of_tracks varchar(20),
  comments varchar(100));

CREATE TABLE ticket_history
( ticket_number varchar(20) PRIMARY KEY,
  status varchar(20),
  ticket_name varchar(20),
  date_opened date,
  date_last_updated date,
  session_date date,
  engineer_name varchar(20),
  engineer_email varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  assignee_name varchar(20),
  assignee_email varchar(20),
  genre varchar(20),
  number_of_tracks varchar(20),
  comments varchar(100));

CREATE TABLE multitracks
( ticket_number varchar(20),
  status varchar(20),
  multitrack_id varchar(20) PRIMARY KEY,
  date_added date,
  date_last_updated date,
  artist varchar(20),
  title varchar(20),
  genre varchar(20),
  number_of_instruments varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  engineer_name varchar(20),
  engineer_email varchar(20),
  mixer_name varchar(20),
  mixer_email varchar(20),
  bouncer_name varchar(20),
  bouncer_email varchar(20),
  comments varchar(100));

CREATE TABLE multitrack_history
( ticket_number varchar(20),
  status varchar(20),
  multitrack_id varchar(20) PRIMARY KEY,
  date_added date,
  date_last_updated date,
  artist varchar(20),
  title varchar(20),
  genre varchar(20),
  number_of_instruments varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  engineer_name varchar(20),
  engineer_email varchar(20),
  mixer_name varchar(20),
  mixer_email varchar(20),
  bouncer_name varchar(20),
  bouncer_email varchar(20),
  comments varchar(100));