CREATE TABLE tickets
  (ticket_number int PRIMARY KEY,
  status varchar(20),
  date_opened date,
  date_last_updated date,
  session_date date,
  session_engineer varchar(20),
  session_engineer_email varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  assignee_name varchar(20),
  assignee_email varchar(20),
  genre varchar(20),
  number_of_tracks int,
  comments varchar(100));

CREATE TABLE ticket_history
( ticket_number int,
  status varchar(20),
  ticket_history_key int PRIMARY KEY,
  date_opened date,
  date_last_updated date,
  session_date date,
  session_engineer varchar(20),
  session_engineer_email varchar(20),
  creator_name varchar(20),
  creator_email varchar(20),
  assignee_name varchar(20),
  assignee_email varchar(20),
  genre varchar(20),
  number_of_tracks int,
  comments varchar(100));

CREATE TABLE multitracks
( ticket_number int,
  status varchar(20),
  multitrack_id int PRIMARY KEY,
  date_added date,
  date_last_updated date,
  artist varchar(20),
  title varchar(20),
  genre varchar(20),
  number_of_instruments int,
  creator_name varchar(20),
  creator_email varchar(20),
  session_engineer_name varchar(20),
  session_engineer_email varchar(20),
  mixing_engineer_name varchar(20),
  mixing_engineer_email varchar(20),
  bouncing_engineer_name varchar(20),
  bouncing_engineer_email varchar(20),
  comments varchar(100));

CREATE TABLE multitrack_history
( ticket_number int,
  status varchar(20),
  multitrack_id int,
  multitrack_history_key int PRIMARY KEY,
  date_added date,
  date_last_updated date,
  artist varchar(20),
  title varchar(20),
  genre varchar(20),
  number_of_instruments int,
  creator_name varchar(20),
  creator_email varchar(20),
  session_engineer_name varchar(20),
  session_engineer_email varchar(20),
  mixing_engineer_name varchar(20),
  mixing_engineer_email varchar(20),
  bouncing_engineer_name varchar(20),
  bouncing_engineer_email varchar(20),
  comments varchar(100));